DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS BUYER;
DROP TABLE IF EXISTS MANAGER;
DROP TABLE IF EXISTS DELIVERER;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS GROCERY_STORE;
DROP TABLE IF EXISTS SYSTEM_INFO;

CREATE TABLE GROCERY_STORE (
	StoreName VARCHAR(20) NOT NULL,
    Street VARCHAR(30),
    City VARCHAR(18),
    Zip CHAR(5),
    State VARCHAR(3),
    Hours_Open TIME,
    Hours_Closed TIME,
    Phone CHAR(10),
    Profit DECIMAL(10,2),
    Total_Items_Sold INT, 
    CONSTRAINT GSPK PRIMARY KEY(StoreName, Street, City, State, Zip)
);

CREATE TABLE USERS (
    Id VARCHAR(20) NOT NULL,
	Username VARCHAR(20) NOT NULL,
	Fname VARCHAR(20),
	Lname VARCHAR(20),
    Pwd VARCHAR(20) NOT NULL,
    Email VARCHAR(30),
    UsrType VARCHAR(15),
    UNIQUE(Username),
    CONSTRAINT USRPK PRIMARY KEY(Id)
);

CREATE TABLE BUYER (
    Id VARCHAR(20) NOT NULL,
    Phone CHAR(10),
	Street VARCHAR(30),
    City VARCHAR(18),
    Zip CHAR(5),
    State VARCHAR(3),
    Account_Num CHAR(14),
    Routing_Num CHAR(9),
    Time_Ordered TIME,
    Date_Ordered DATE,
    Total_Price DECIMAL(10,2),
    Total_Num_Items INT,
	CONSTRAINT BUYERFK FOREIGN KEY(Id) REFERENCES USERS(Id) ON DELETE CASCADE ON UPDATE CASCADE
);
    
CREATE TABLE MANAGER (
	Id CHAR(20) NOT NULL,
    StoreName VARCHAR(20),
    Street VARCHAR(30),
    City VARCHAR(18),
    Zip CHAR(5),
    State VARCHAR(3),
    CONSTRAINT MGRFK1 FOREIGN KEY(Id) REFERENCES USERS(Id) ON DELETE CASCADE ON UPDATE CASCADE, 
    CONSTRAINT MGRFK2 FOREIGN KEY(StoreName, Street, City, State, Zip) REFERENCES GROCERY_STORE(StoreName, Street, City, State, Zip) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DELIVERER (
	Id CHAR(20) NOT NULL,
    Deliver_Feedback VARCHAR(100),
    Deliver_Instruct VARCHAR(100),
    CONSTRAINT DELIVFK FOREIGN KEY(Id) REFERENCES USERS(Id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ITEM (
	Id CHAR(20) NOT NULL,
    Item_Name VARCHAR(20),
    Item_Group VARCHAR(30),
    Expiration_Date DATE,
    Quantity INT,
    Listed_Price DECIMAL(10,2),
    Wholesale_Price DECIMAL(10,2),
    Item_Desciption VARCHAR(50),
    In_Stock_Store VARCHAR(20),
    In_Stock_Street VARCHAR(30),
    In_Stock_City VARCHAR(18),
    In_Stock_Zip CHAR(5),
    In_Stock_State VARCHAR(3),
    CONSTRAINT ITEMPK PRIMARY KEY(Id),
    CONSTRAINT ITEMFK FOREIGN KEY(In_Stock_Store, In_Stock_Street, In_Stock_City, In_Stock_State, In_Stock_Zip) REFERENCES GROCERY_STORE(StoreName, Street, City, State, Zip) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ORDERS (
	Id CHAR(20) NOT NULL,
    Total_Price DECIMAL(10,2),
    Total_Num_Items INT,
    Deliverer_Id CHAR(20) NOT NULL,
    Deliverer_Feedback VARCHAR(100),
    Delivered BOOL,
    CONSTRAINT ORDERPK PRIMARY KEY(Id),
    CONSTRAINT ORDERFK FOREIGN KEY(Deliverer_Id) REFERENCES DELIVERER(Id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SYSTEM_INFO (
	DelivererPwd VARCHAR(20) NOT NULL,
    MgrPwd VARCHAR(20) NOT NULL
);